### ISSUE TITLE
[Bug] Copy & Paste bug

### ISSUE THREAD

**Issue by Erkam246** [thebigsmileXD/MagicWE2#175]
- Newest version

**Comment by inxomnyaa** [comment]
Please properly include the output of //version. I can not watch videos, sorry. Please describe as text.

**Comment by Aericio** [comment]
Essentially, he was trying to copy and paste an island and nothing was pasting.
![image](https://user-images.githubusercontent.com/16523741/74095538-58960d00-4a96-11ea-983f-6d1e958f8fc0.png)

Also, please don't include sound clips into a video where you're trying to describe a bug. It's annoying and unnecessary.

**Comment by inxomnyaa** [comment]
If nothing is pasting, that is due to getTouchedChunks getting the wrong chunks (i have trouble with the offset, if i do add the offset, the shape object is modified)
I think i have a mild understanding what causes it, and maybe i can implement a workaround.
I have debugged the "paste chunks" vs "paste position" via libstructure + a custom plugin, that implements some WE test commands, to display a frame around both the paste position and the chunks returned by getTouchedChunks
Temporarily you could work around it by standing at 258 45 273 when doing //copy

**Comment by inxomnyaa** [comment]
Please give the latest build a try - i have tested with a [x,y,z]=[3,1,3] sized shape with:
- copy and paste position equal
- copy and paste chunks equal (fly up/down, move some blocks WASD)
- copy from another chunk, paste in the chunk where i used //copy in AND any other chunks (also the chunk where the structure was located in)
- copy with negative and positive offset (i.e. +20 blocks every direction vs -20 blocks)
- pasting several times in a row, in same and different positions
- using copy several times in a row, or using //copy after every //paste (this results in just the same paste position every time :P)
I haven't found an issue with that, but i have not done large scale operations yet
